dataset: "LJSpeech"

path:
  corpus_path: "/data_mnt/LJSpeech-1.1"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/LJSpeech"
  preprocessed_path: "./preprocessed_data/LJSpeech"
  wav2vec2_path: '/data_mnt/wav2vec2_large_960h'
  

preprocessing:
  val_size: 100
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
 
  w2v:
    sampling_rate: 16000
    n_channels: 1024

 
