dataset: "VCTK"

path:
  corpus_path: "/data_mnt/VCTK/"
  lexicon_path: "lexicon/en_lexicon.txt"
  raw_path: "./raw_data/VCTK"
  preprocessed_path: "./preprocessed_data/VCTK"
  wav2vec2_path: '/data_mnt/wav2vec2_large_960h'

preprocessing:
  val_size: 200
  text:
    text_cleaners: []
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  w2v:
    sampling_rate: 16000
    n_channels: 1024
