dataset: "AISHELL3"

path:
  corpus_path: "/data_mnt/aishell3"
  lexicon_path: "lexicon/pinyin-lexicon-r.txt"
  raw_path: "./raw_data/AISHELL3"
  preprocessed_path: "./preprocessed_data/AISHELL3"
  wav2vec2_path: '/data_mnt/wav2vec2_large_960h'


preprocessing:
  val_size: 800
  text:
    text_cleaners: []
    language: "zh"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80 #80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  w2v:
    sampling_rate: 16000
    n_channels: 1024
